"""modified_health_metrics

Revision ID: 1357e966de1e
Revises: 462f6dc71bcd
Create Date: 2024-03-13 15:41:53.984822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1357e966de1e'
down_revision = '462f6dc71bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.alter_column('metric_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_metrics', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('metric_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
