"""prescription_time_nullable

Revision ID: 22fe252503a2
Revises: b297f92f46e2
Create Date: 2024-03-19 08:46:17.820935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fe252503a2'
down_revision = 'b297f92f46e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('time_of_day',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('time_of_day',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
