"""empty message

Revision ID: 7223162283b7
Revises: 1357e966de1e
Create Date: 2024-03-14 13:51:49.714518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7223162283b7'
down_revision = '1357e966de1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_types', schema=None) as batch_op:
        batch_op.drop_column('units')

    # ### end Alembic commands ###
