"""empty message

Revision ID: 94e66f43bd04
Revises: 7223162283b7
Create Date: 2024-03-15 17:12:21.641471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e66f43bd04'
down_revision = '7223162283b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('prescribed_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescribed_on', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
