"""empty message

Revision ID: b297f92f46e2
Revises: 94e66f43bd04
Create Date: 2024-03-17 16:24:49.297782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b297f92f46e2'
down_revision = '94e66f43bd04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_names', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('drug_class', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('box_warning', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('indications', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dosages', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contraindications_and_cautions', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('adverse_effects', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('administration', sa.String(), nullable=True))
        batch_op.drop_column('adverse_reactions')
        batch_op.drop_column('dosage_and_administration')
        batch_op.drop_column('warnings_and_cautions')
        batch_op.drop_column('route')
        batch_op.drop_column('contraindications')
        batch_op.drop_column('boxed_warning')
        batch_op.drop_column('pharm_class')
        batch_op.drop_column('indications_and_usage')
        batch_op.drop_column('description')
        batch_op.drop_column('brand_name')
        batch_op.drop_column('pregnancy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pregnancy', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('brand_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('indications_and_usage', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pharm_class', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('boxed_warning', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('contraindications', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('route', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('warnings_and_cautions', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('dosage_and_administration', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('adverse_reactions', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('administration')
        batch_op.drop_column('adverse_effects')
        batch_op.drop_column('contraindications_and_cautions')
        batch_op.drop_column('dosages')
        batch_op.drop_column('indications')
        batch_op.drop_column('box_warning')
        batch_op.drop_column('drug_class')
        batch_op.drop_column('brand_names')

    # ### end Alembic commands ###
