"""update metric_types

Revision ID: c9540c45263a
Revises: bf1bb0f4a86e
Create Date: 2024-05-09 16:53:29.133724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9540c45263a'
down_revision = 'bf1bb0f4a86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_types', schema=None) as batch_op:
        batch_op.drop_column('yellow_params')
        batch_op.drop_column('green_params')
        batch_op.drop_column('red_params')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('red_params', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('green_params', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('yellow_params', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
