"""modified metric_type

Revision ID: da64a1a2367e
Revises: 7ccf07ea3773
Create Date: 2024-03-13 14:03:51.668055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da64a1a2367e'
down_revision = '7ccf07ea3773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yellow_params', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('red_params', sa.Integer(), nullable=True))
        batch_op.drop_column('yellow_params_high')
        batch_op.drop_column('red_params_high')
        batch_op.drop_column('yellow_params_low')
        batch_op.drop_column('red_params_low')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('red_params_low', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('yellow_params_low', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('red_params_high', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('yellow_params_high', sa.INTEGER(), nullable=True))
        batch_op.drop_column('red_params')
        batch_op.drop_column('yellow_params')

    # ### end Alembic commands ###
